# Use the official Python image as the base image
FROM python:3.11-slim

# Set environment variables
ENV PORT=5000

# Set the working directory
WORKDIR /

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libffi-dev \
    libssl-dev \
    libportaudio2 \
    portaudio19-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*


RUN pip install --upgrade pip

# Copy the requirements file
COPY requirements.txt ./


RUN pip install --no-cache-dir -r requirements.txt


# Copy the rest of the application code
COPY . .

# Expose the application port
EXPOSE $PORT

# Command to run the FastAPI application using a standard Python web server (like uvicorn)
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]