# Use the official Python image as the base image
FROM python:3.11-slim

# Set environment variables

ENV PORT=5000

# Set the working directory
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libffi-dev \
    libssl-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

    # Install uv
RUN curl -LsSf https://astral.sh/uv/install.sh | sh && \
echo 'export PATH="/root/.local/bin:$PATH"' >> /etc/profile && \
export PATH="/root/.local/bin:$PATH"

# Verify uv installation
RUN uv --version
# Ensure uv is available
ENV PATH="/root/.local/bin:${PATH}"

# Set the working directory

# Copy the requirements file
COPY requirements.txt ./
RUN uv pip sync requirements.txt --system


# Copy the application code
COPY . .

# Expose the application port
EXPOSE $PORT

# Command to run the FastAPI application
CMD ["uv", "fastapi", "app.main:app", "--host", "0.0.0.0", "--port", "5000"]